[opcache]
opcache.enable=1
; 0 means it will check on every request
; 0 is optimal for production but means you must restart PHP when files change
opcache.validate_timestamps=0
; maximum memory that OPcache can use to store compiled PHP files
opcache.memory_consumption=256
; maximum number of files that can be stored in the cache
opcache.max_accelerated_files=20000
; maximum memory allocated to store the results
opcache.interned_strings_buffer=16
opcache.fast_shutdown=1
